### ISSUE TITLE
Why the key comparison of the defense performance is distinctly different from the DBD publication? It's the same configuration, almost dataset, attack strategy, and hyperparameter!

### ISSUE THREAD

**Issue by Chen-Zhiwei** [KuofengGao/ASD#2]
Why the key comparison of the defense performance is distinctly different from the DBD publication? It's the same configuration, almost dataset, attack strategy, and hyperparameter!
your paper:
![image](https://github.com/KuofengGao/ASD/assets/61465354/75940106-9368-4884-b0c0-98a5c32c3792)
DBD:
![image](https://github.com/KuofengGao/ASD/assets/61465354/ba3f4235-b042-4887-9bd2-fe200dde1518)

**Comment by KuofengGao** [comment]
Hi, thanks for

**Comment by KuofengGao** [comment]
Hi, thanks for your attention for our work. We will do our best to solve your questions point by point.

First, both our study and DBD employ a subset of the ImageNet dataset, with 30 categories randomly selected from the original ImageNet dataset. It is worth noting that this could lead to **a difference in the specific dataset used**.

Secondly, we reproduce the experiment of DBD many times and the ASR of Blend is still 100% on the selected ImageNet dataset. During the experiment, we observe that the Blend backdoor attack is able to implant the backdoor successfully during **the second stage of the DBD**, resulting in an ASR of 100%. The reason is that the linear layer is **fine-tuned on the whole poisoned dataset** in the second stage of DBD and this is enough to finish the attack for the Blend trigger. This suggests that the Blend trigger is a potent attack that can bypass the defense mechanisms of DBD. 

I'm happy to help with any further inquiries you may have.
